sudo: required

services: 
  - docker 


before_install:
  - docker build -t mesutacerpro/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true mesutacerpro/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-601871475248"
  bucket_path: "docker-react"
  on: 
    branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY